placeholders:
    scripts_after:
        items:
            sync_js:
                order: 310
            maintenance_js:
                order: 220
            ping_js:
                order: 230

items:
    sync_js:
        template: OroSyncBundle::sync_js.html.twig
        applicable: "@oro_security.security_facade->hasLoggedUser()"
    maintenance_js:
        template: OroSyncBundle::maintenance_js.html.twig
    ping_js:
        template: OroSyncBundle::ping_js.html.twig
